project_name: serverless-calculator
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
dockers:
- image_templates: ["ghcr.io/ranggarppb/serverless-calculator:{{ .Version }}"]
  dockerfile: Dockerfile
  build_flag_templates:
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/ranggarppb/serverless-calculator
  - --label=org.opencontainers.image.source=https://github.com/ranggarppb/serverless-calculator
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2023-09-17T17:57:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
nfpms:
- maintainer: Rangga Putra Pertama <ranggaputrapertamapp@gmail.com>
  description: Sample project.
  homepage: https://github.com/ranggarppb/serverless-calculator
  license: MIT
  formats:
  - deb
  - rpm
  - apk
