// Code generated by mockery v2.32.3. DO NOT EDIT.

package mocks

import (
	errors "github.com/ranggarppb/serverless-calculator/errors"
	mock "github.com/stretchr/testify/mock"
)

// ICalculatorService is an autogenerated mock type for the ICalculatorService type
type ICalculatorService struct {
	mock.Mock
}

// Calculate provides a mock function with given fields: input
func (_m *ICalculatorService) Calculate(input string) (string, errors.WrappedError) {
	ret := _m.Called(input)

	var r0 string
	var r1 errors.WrappedError
	if rf, ok := ret.Get(0).(func(string) (string, errors.WrappedError)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) errors.WrappedError); ok {
		r1 = rf(input)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.WrappedError)
		}
	}

	return r0, r1
}

// GetCalculationHistory provides a mock function with given fields:
func (_m *ICalculatorService) GetCalculationHistory() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// NewICalculatorService creates a new instance of ICalculatorService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICalculatorService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICalculatorService {
	mock := &ICalculatorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
